version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
    pdfapi:
        image: microbox/node-url-to-pdf-api
        container_name: pdfapi
        restart: unless-stopped
        tty: true
        ports:
            - '8404:80'
        networks:
            - app-network
    websocketserver:
        image: 'centrifugo/centrifugo:v2.2.4'
        container_name: websocketserver
        restart: unless-stopped->phonename
        tty: true
        environment:
            - CENTRIFUGO_SECRET=${CENTRIFUGO_SECRET}
            - CENTRIFUGO_ADMIN_PASSWORD=${CENTRIFUGO_ADMIN_PASSWORD}
            - CENTRIFUGO_ADMIN_SECRET=${CENTRIFUGO_ADMIN_SECRET}
        ports:
            - '8800:8000'
        command: centrifugo --config=config.json --admin --debug=true --name="gorocket_1"
        volumes:
            - './centrifugo/centrifugo.json:/centrifugo/config.json'
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
volumes:
    esdata:
        driver: local
